### ISSUE TITLE
Outdated dependency on fractions?

### ISSUE THREAD

**Issue by ftrotta** [lime-green/remote-docker-aws#22]
Hello there.

I'm running your tool on a Macbook with macOS Big Sur 11.1.
The output follows.

Is there any outdated dependency on fraction package?

Thanks

```
[user]@[host] ~ % remote-docker-aws create-keypair
Traceback (most recent call last):
  File "/Users/[user]/.local/bin/remote-docker-aws", line 5, in <module>
    from remote_docker_aws.main import main
  File "/Users/[user]/.local/pipx/venvs/remote-docker-aws/lib/python3.9/site-packages/remote_docker_aws/main.py", line 1, in <module>
    from .cli_commands import cli
  File "/Users/[user]/.local/pipx/venvs/remote-docker-aws/lib/python3.9/site-packages/remote_docker_aws/cli_commands.py", line 4, in <module>
    from .core import (
  File "/Users/[user]/.local/pipx/venvs/remote-docker-aws/lib/python3.9/site-packages/remote_docker_aws/core.py", line 10, in <module>
    from sceptre.cli.helpers import setup_logging
  File "/Users/[user]/.local/pipx/venvs/remote-docker-aws/lib/python3.9/site-packages/sceptre/cli/__init__.py", line 19, in <module>
    from sceptre.cli.create import create_command
  File "/Users/[user]/.local/pipx/venvs/remote-docker-aws/lib/python3.9/site-packages/sceptre/cli/create.py", line 5, in <module>
    from sceptre.plan.plan import SceptrePlan
  File "/Users/[user]/.local/pipx/venvs/remote-docker-aws/lib/python3.9/site-packages/sceptre/plan/plan.py", line 12, in <module>
    from sceptre.config.graph import StackGraph
  File "/Users/[user]/.local/pipx/venvs/remote-docker-aws/lib/python3.9/site-packages/sceptre/config/graph.py", line 11, in <module>
    import networkx as nx
  File "/Users/[user]/.local/pipx/venvs/remote-docker-aws/lib/python3.9/site-packages/networkx/__init__.py", line 114, in <module>
    import networkx.generators
  File "/Users/[user]/.local/pipx/venvs/remote-docker-aws/lib/python3.9/site-packages/networkx/generators/__init__.py", line 14, in <module>
    from networkx.generators.intersection import *
  File "/Users/[user]/.local/pipx/venvs/remote-docker-aws/lib/python3.9/site-packages/networkx/generators/intersection.py", line 13, in <module>
    from networkx.algorithms import bipartite
  File "/Users/[user]/.local/pipx/venvs/remote-docker-aws/lib/python3.9/site-packages/networkx/algorithms/__init__.py", line 16, in <module>
    from networkx.algorithms.dag import *
  File "/Users/[user]/.local/pipx/venvs/remote-docker-aws/lib/python3.9/site-packages/networkx/algorithms/dag.py", line 23, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/fractions.py)
```

```
[user]@[host] ~ % remote-docker-aws create
Traceback (most recent call last):
  File "/Users/[user]/.local/bin/remote-docker-aws", line 5, in <module>
    from remote_docker_aws.main import main
  File "/Users/[user]/.local/pipx/venvs/remote-docker-aws/lib/python3.9/site-packages/remote_docker_aws/main.py", line 1, in <module>
    from .cli_commands import cli
  File "/Users/[user]/.local/pipx/venvs/remote-docker-aws/lib/python3.9/site-packages/remote_docker_aws/cli_commands.py", line 4, in <module>
    from .core import (
  File "/Users/[user]/.local/pipx/venvs/remote-docker-aws/lib/python3.9/site-packages/remote_docker_aws/core.py", line 10, in <module>
    from sceptre.cli.helpers import setup_logging
  File "/Users/[user]/.local/pipx/venvs/remote-docker-aws/lib/python3.9/site-packages/sceptre/cli/__init__.py", line 19, in <module>
    from sceptre.cli.create import create_command
  File "/Users/[user]/.local/pipx/venvs/remote-docker-aws/lib/python3.9/site-packages/sceptre/cli/create.py", line 5, in <module>
    from sceptre.plan.plan import SceptrePlan
  File "/Users/[user]/.local/pipx/venvs/remote-docker-aws/lib/python3.9/site-packages/sceptre/plan/plan.py", line 12, in <module>
    from sceptre.config.graph import StackGraph
  File "/Users/[user]/.local/pipx/venvs/remote-docker-aws/lib/python3.9/site-packages/sceptre/config/graph.py", line 11, in <module>
    import networkx as nx
  File "/Users/[user]/.local/pipx/venvs/remote-docker-aws/lib/python3.9/site-packages/networkx/__init__.py", line 114, in <module>
    import networkx.generators
  File "/Users/[user]/.local/pipx/venvs/remote-docker-aws/lib/python3.9/site-packages/networkx/generators/__init__.py", line 14, in <module>
    from networkx.generators.intersection import *
  File "/Users/[user]/.local/pipx/venvs/remote-docker-aws/lib/python3.9/site-packages/networkx/generators/intersection.py", line 13, in <module>
    from networkx.algorithms import bipartite
  File "/Users/[user]/.local/pipx/venvs/remote-docker-aws/lib/python3.9/site-packages/networkx/algorithms/__init__.py", line 16, in <module>
    from networkx.algorithms.dag import *
  File "/Users/[user]/.local/pipx/venvs/remote-docker-aws/lib/python3.9/site-packages/networkx/algorithms/dag.py", line 23, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/fractions.py)
```

**Comment by lime-green** [comment]
@ftrotta heya. Python 3.9 doesn't work at the moment because of: https://github.com/Sceptre/sceptre/issues/942

Since it looks like it's going to take a while for the change to make its way into a sceptre release, I'm going to look into getting this fixed. In the meantime, you can use python 3.8 instead if that's option.

**Comment by lime-green** [comment]
Thanks @ftrotta, the 2.3.0 release fixes this
